In [1]:
import numpy as np
import pandas as pd
! pip install sympy
from sympy import *
from scipy.linalg import lu 

Defaulting to user installation because normal site-packages is not writeable


# a. Read a matrix A from a csv file and a vector b from another csv file 

In [2]:
matrix=pd.read_csv('/home/sai/Documents/Matrix.csv')
A=pd.read_csv("/home/sai/Documents/A.csv")
b=pd.read_csv("/home/sai/Documents/b.csv")
#print("matrix:---------------")
#print(matrix)
print("A:---------------")
print(A)
print("b:---------------")
print(b)

A:---------------
   1  2   3
0  8  3  -2
1 -4  7   5
2  3  4 -12
b:---------------
   0  Unnamed: 1  Unnamed: 2
0  9          15          35


# b. Perform LU decomposition for square matrix

In [3]:
#  Do the matrix factorization.  In our case, the permutation matrix P is the identity
P, L, U = lu(A)
print('The L matrix is:')
print(L)
print()
print('The U matrix is:')
print(U)

#  Show the A = PLA
res=np.dot(P,L)
a=np.dot(res,U)
print("A:", a)


The L matrix is:
[[ 1.          0.          0.        ]
 [-0.5         1.          0.        ]
 [ 0.375       0.33823529  1.        ]]

The U matrix is:
[[  8.           3.          -2.        ]
 [  0.           8.5          4.        ]
 [  0.           0.         -12.60294118]]
A: [[  8.   3.  -2.]
 [ -4.   7.   5.]
 [  3.   4. -12.]]


#   c.  Solve the equation Ax=b and check whether there are 0,1 or infinitely many solutions


In [4]:
A=np.array(A)
b=np.array(b).T
print("A:", A)
print("--------------------")
print("b:",b)
print("--------------------")

rank_A=np.linalg.matrix_rank(A)

aug_A=np.column_stack((A,b))

rank_aug_A=np.linalg.matrix_rank(aug_A)
#print(rank_aug_A)
#print(type(rank_aug_A))

if (rank_A==rank_aug_A) and (rank_aug_A==np.shape(A)[0]):
    print("The system has a unique solution\n.")
    
elif (rank_A==rank_aug_A) and (rank_aug_A< np.shape(A)[0]):
    print("The system has ∞-many solutions.")
    
if(rank_A < rank_aug_A):
    print(" The system is inconsistent..")

print("solve the AX=b equation------------------\n")
x = np.linalg.solve(A, b)
print("X:",x)

A: [[  8   3  -2]
 [ -4   7   5]
 [  3   4 -12]]
--------------------
b: [[ 9]
 [15]
 [35]]
--------------------
The system has a unique solution
.
solve the AX=b equation------------------

X: [[-0.58226371]
 [ 3.22870478]
 [-1.98599767]]


#   d.Do the diagonalization of a matrix (assume it is symmetric)

In [7]:
#diagonilization of a matrix
M=Matrix(A)
print(M)
P, D = M.diagonalize()  
print(D)

Matrix([[8, 3, -2], [-4, 7, 5], [3, 4, -12]])
Matrix([[1 - 129/((-1/2 - sqrt(3)*I/2)*(27*sqrt(213413)/2 + 19683/2)**(1/3)) - (-1/2 - sqrt(3)*I/2)*(27*sqrt(213413)/2 + 19683/2)**(1/3)/3, 0, 0], [0, 1 - (-1/2 + sqrt(3)*I/2)*(27*sqrt(213413)/2 + 19683/2)**(1/3)/3 - 129/((-1/2 + sqrt(3)*I/2)*(27*sqrt(213413)/2 + 19683/2)**(1/3)), 0], [0, 0, -(27*sqrt(213413)/2 + 19683/2)**(1/3)/3 - 129/(27*sqrt(213413)/2 + 19683/2)**(1/3) + 1]])


# e. Give exponential, sine and sigmoid functions on A

In [ ]:
def sigmoid(x):
    return(1/(1 + np.exp(-x)))
def exponenstial(x):
    return np.exp(x)
def sinfun(x):
    return np.sin(x)

sig=[sigmoid(i) for i in A]
expo=[exponenstial(i) for i in A]
sinf=[sinfun(i) for i in A]
print("sigmoid function----------")
print(np.array(sig))
print("exponential function----------")
print(np.array(expo))
print("sin function----------")
print(np.array(sinf))


# f.Find all the eigenpairs of A

In [ ]:
#calculate eigenpairs
valus,vectors=np.linalg.eig(A)
print(" Eigen Values are", valus)
print("Eigen Vactors are",vectors)