In [1]:
import numpy as np
import pandas as pd
! pip install sympy
from sympy import *
from scipy.linalg import lu 

Defaulting to user installation because normal site-packages is not writeable


# a. Read a matrix A from a csv file and a vector b from another csv file 

In [2]:
matrix=pd.read_csv("/home/sai/Documents/Matrix.csv")
print(matrix)

   Unnamed: 0  Unnamed: 1  Unnamed: 2
0           4           1          -1
1           2           5          -2
2           1           1           2


In [4]:
mat=np.array(matrix)
print(mat)

[[ 4  1 -1]
 [ 2  5 -2]
 [ 1  1  2]]


# b. Perform LU decomposition for square matrix

In [6]:
#  Do the matrix factorization.  In our case, the permutation matrix P is the identity
P, L, U = lu(mat)
print('The L matrix is:')
print(L)
print()
print('The U matrix is:')
print(U)

#  Show the A = PLA
np.allclose(L @ U, mat)

The L matrix is:
[[1.         0.         0.        ]
 [0.5        1.         0.        ]
 [0.25       0.16666667 1.        ]]

The U matrix is:
[[ 4.   1.  -1. ]
 [ 0.   4.5 -1.5]
 [ 0.   0.   2.5]]


True

#   Solve the equation Ax=b 

In [7]:
n=int(input("Enter number of row and column"))
print("enter the  co efficient of matrix: A")
A=[[int(input())for i in range(n)]for j in range(n)]
print("enter the  of matrix: b")
b=[int(input()) for i in range(n)]
A=np.array(A)
b=np.array(b)
print("A:", A)
print("--------------------")
print("b:",b)
print("--------------------")

#solve the AX=b equation
x = np.linalg.solve(A, b)
print("X:",x)

Enter number of row and column3
enter the  co efficient of matrix: A
8
3
-2
-4
7
5
3
4
-12
enter the  of matrix: b
9
15
35
A: [[  8   3  -2]
 [ -4   7   5]
 [  3   4 -12]]
--------------------
b: [ 9 15 35]
--------------------
X: [-0.58226371  3.22870478 -1.98599767]


#   Do the diagonalization of a matrix (assume it is symmetric)

In [8]:
#diagonilization of a matrix
M=Matrix(mat)
print(M)
P, D = M.diagonalize()  
print(D)

Matrix([[4, 1, -1], [2, 5, -2], [1, 1, 2]])
Matrix([[3, 0, 0], [0, 3, 0], [0, 0, 5]])


# Find all the eigenpairs of A

In [10]:
#calculate eigenpairs
valus,vectors=np.linalg.eig(mat)
print(" Eigen Values are", valus)
print("Eigen Vactors are",vectors)

 Eigen Values are [5. 3. 3.]
Eigen Vactors are [[ 0.40824829  0.40824829  0.20788451]
 [ 0.81649658 -0.81649658  0.57986183]
 [ 0.40824829 -0.40824829  0.78774634]]
