In [1]:
import numpy as np
import pandas as pd
from scipy.linalg import lu 

In [2]:
matrix=pd.read_csv("/home/sai/Documents/Matrix.csv")
print(matrix)

   Unnamed: 0  Unnamed: 1  Unnamed: 2
0           4           1          -1
1           2           5          -2
2           1           1           2


In [3]:
A=np.array(matrix)
print(A)

[[ 4  1 -1]
 [ 2  5 -2]
 [ 1  1  2]]


In [4]:
#  Do the matrix factorization.  In our case, the permutation matrix P is the identity
P, L, U = lu(A)
print('The L matrix is:')
print(L)
print()
print('The U matrix is:')
print(U)

#  Show the A = PLA
np.allclose(L @ U, A)

The L matrix is:
[[1.         0.         0.        ]
 [0.5        1.         0.        ]
 [0.25       0.16666667 1.        ]]

The U matrix is:
[[ 4.   1.  -1. ]
 [ 0.   4.5 -1.5]
 [ 0.   0.   2.5]]


True

In [5]:
#calculate eigenpairs
valus,vectors=np.linalg.eig(A)
print(" Eigen Values are", valus)
print("Eigen Vactors are",vectors)

 Eigen Values are [5. 3. 3.]
Eigen Vactors are [[ 0.40824829  0.40824829  0.20788451]
 [ 0.81649658 -0.81649658  0.57986183]
 [ 0.40824829 -0.40824829  0.78774634]]


In [7]:
#diagonilization of a matrix
P, D = A.diagonalize()  

AttributeError: 'numpy.ndarray' object has no attribute 'diagonalize'